### ISSUE TITLE
SRE / DevOps Engineer at Liquibase

### ISSUE THREAD

**Issue by jnewton03** [Austin-Devops/atxdevops-job-board#27]
Company Name: Liquibase
Location: Austin "based".  Fully remote position for an Austin-based company.
Job Title: SRE / DevOps Engineer
Role description: Small company, so you will wear the hat of SRE and DevOps Engineer.  We have a greenfield SaaS app where the SRE role comes into play, but we also have a couple of on-prem applications.
Do you allow remote?: We are fully remote.
Link to job: [Liquibase SRE / DevOps](https://www.liquibase.com/company/careers#positions?gh_jid=2330202)

**Comment by jnewton03** [comment]
@zfouts you interested?

**Comment by zfouts** [comment]
@jnewton03 sure! please reach out to me on slack

**Comment by jnewton03** [comment]
@zfouts how do I get a login for hangops?

**Comment by zfouts** [comment]
> @zfouts how do I get a login for hangops?

@jnewton03 https://signup.hangops.com/
#atxdevops is the channel

my name is @zfouts on there
