### ISSUE TITLE
k8s Chaos Software Engineer - Verica

### ISSUE THREAD

**Issue by ernestm** [Austin-Devops/atxdevops-job-board#28]
**Company Name:** Verica
**Location:** Remote (we have 5 Austinites so far, but we're 100% remote)
**Job Title:** Senior Software Engineer (we don't use levels)
**Role Description:** 

Verica is a small, well funded startup creating a software platform to perform chaos engineering experiments for complex systems at enterprise customers.  Starting out, that means kafka and kubernetes, with more to come. Casey, our CEO, ran chaos engineering at Netflix. We're still pre-GA, 17 people up from 10 when I started 3 months ago, hiring vigorously. We value work/life balance, diversity, and helping the world become better through resilience!

I have several positions open for senior software engineers with unusually deep k8s experience, to invent kubernetes chaos experiments that help people increase the resilience of and trust in their systems, and implement them (platform's in python3, and lots of k8s-side work in Go with operators and whatnot). The ideal candidate is an experienced developer (this isn't a DevOps/SRE position) that has contributed to commercial or open source k8s/CNCF products and has real world experience with kubernetes running at significant scale and having subtle problems. 

**Salary Range:** Per applicant.  Salary + equity, fully paid for medical.
**Do you allow remote?:** Yes, remote only.
**Link to job:** The job isn't publicly posted, you can apply or let me know about someone else I should talk to by contacting ernest at verica dot io and I'll chat with you!  Or hit me at @emueller on hangops slack.

**Comment by zfouts** [comment]
Please post your slack handle in the job description so we can reach out to you directly (assuming job req is still open)

**Comment by ernestm** [comment]
Job still open, I have 3 more k8s engineers to hire!  We're now at 22 people total in the company since last post.

**Comment by ernestm** [comment]
Job still open, I have 2 more k8s developers to hire!
