### ISSUE TITLE
Zebra SRE Role

### ISSUE THREAD

**Issue by Skenkel** [Austin-Devops/atxdevops-job-board#5]
**Company Name**:  The Zebra
**Location**: Austin - East Side (1801 East 6th Street)
**Job Title**: Site Reliability Engineer (SRE)
**Role description**: The primary role of this person is to support the development organization by ensuring and maintaining infrastructure uptime.  The SRE responds to all system alerts and alarms, providing triaging, resolution and communication to all stakeholders. Experience with Python, K8s & AWS.
**Salary Range**: Competitive
**Do you allow remote?**: No, we do allow WFH but we would like this person to be onsite at our new office
**Link to job**: https://jobs.lever.co/thezebra/e876b083-64f4-4b1f-acf8-dc1c09fadec4

**Comment by zfouts** [comment]
@Skenkel still valid? Sorry I missed your issue!

**Comment by zfouts** [comment]
Closing
```
Sorry, we couldn't find anything here
The job posting you're looking for might have closed, or it has been removed. (404 error).
```
