### ISSUE TITLE
Sr. DevOps Engineer - Sila Money Inc. - Remote

### ISSUE THREAD

**Issue by BruceHohensee** [Austin-Devops/atxdevops-job-board#50]
Sila Money Inc.
Remote in the US.
Sr. DevOps Engineer
We are seeking an experienced DevOps Engineer to help us keep growing. As part of the engineering team, you will be responsible for automating deployments, managing infrastructure, monitoring and reviewing logs, ensuring that security controls are implemented in compliance with security requirements and best practices. This role will be remote, our core team is in the Portland, OR  area.
$115-145K, stock option, unlimited time off
We are based in Portland, OR, but our team is remote across the US.
https://silamoney.applytojob.com/apply/k0ZeigUu22/Sr-DevOps-Engineer?source=GitHub-Austin

**Comment by zfouts** [comment]
This position is no longer available.
