### ISSUE TITLE
Sr. Devops Engineer @ HardRockDigital

### ISSUE THREAD

**Issue by bparafina** [Austin-Devops/atxdevops-job-board#51]
## Company Name
Hard Rock Digital

## Location
Austin based
Flexible work from home or office hours

## Job Title
Sr. Devops Engineer

## Role description

The ideal candidate will have:
    7+ years of experience in DevOps or similar role
    Extensive experience working with AWS
    Experience working in non-cloud virtualization (eg VMWare, etc)
    Experience with containerization (Docker, Kubernetes, etc)
    Experience developing infrastructure with Terraform, Ansible, Salt, Cloud Formation or similar tools
    Experience with Python and Shell scripting
    AWS certification is a plus

## Salary Range
120k/yr - 150k/yr

## Do you allow remote?
yes, full time

## Link to job
https://www.hardrockdigital.com/#job-720040

**Comment by zfouts** [comment]
Looks like two are available still, at different URLs:
https://www.hardrockdigital.com/#job-867349
https://www.hardrockdigital.com/#job-854697

Leaving open
