### ISSUE TITLE
Sr. Devops Engineer

### ISSUE THREAD

**Issue by daniel-kadosh-gartner** [Austin-Devops/atxdevops-job-board#6]
## Company Name
Gartner / Software Advice

## Location
Currently in SoCo:  200 Academy Dr #120, Austin, TX 78704
Moving around May 2020 to Mopac & Bee Caves:  2500 Bee Caves Rd, Austin, TX 78746

## Job Title
Sr DevOps Engineer

## Role description
Cloud architecture and management of CI/CD systems in AWS.  See job link for details.

## Salary Range
Competitive, with above-average benefits.

## Do you allow remote?
We have flexible schedules, but mostly in-office.

## Link to job
https://jobs.gartner.com/job/austin/sr-devops-engineer/494/14247521

**Comment by zfouts** [comment]
@daniel-kadosh-gartner sorry that I missed this.

FYI looks like job is still open as of January 12, 2020.

**Comment by daniel-kadosh-gartner** [comment]
Yep, it's still open!
